target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
  "ANN",    # flake8-annotations (ANN)
  "COM812", # missing-trailing-comma
  "D",      # pydocstyle (D)
  "RET504", # Unnecessary assignment to X before `return` statement
]

[lint.per-file-ignores]
"tests/**" = ["S101"]  # assert is expected in tests
